server:
  port: 8080
 
eureka:
  instance:
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: 'http://www2-optux.herokuapp.com/eureka/'
 
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: employeeModule
        uri: lb://KENZAN
        predicates:
          - Path=/employee/**
